# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SB_UV6qTnioxCUOMwIZFlRbTGuNNze51
"""

!pip install pandas scikit-learn openpyxl
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_excel('/content/100 lines.xlsx', sheet_name='Sheet1')

print(df.head())

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['EnglishTranslation'])

# Define a single query
query = "What is charity?"

# Transform the query to vector
query_vector = vectorizer.transform([query])

# Compute cosine similarities
cosine_similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()

# Find the indices of the top 3 most similar documents
top_sim_indices = cosine_similarities.argsort()[-3:][::-1]

# Print the results with serial numbers
for i, sim_idx in enumerate(top_sim_indices):
    print(f"Most similar document {i+1}: SrNo {df['SrNo'].iloc[sim_idx]}")
    print(f"English Translation: {df['EnglishTranslation'].iloc[sim_idx]}")
    print(f"Similarity Score: {cosine_similarities[sim_idx]}")
    print()